services:

  nginx:
    build:
      context: ./src
      dockerfile: Dockerfile-Ubuntu-Nginx
    container_name: masscan-web
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html  
    restart: always

  fpm:
    build:
      context: ./src
      dockerfile: Dockerfile-PHP-FPM
    container_name: masscan-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    restart: always

  mysql:
    image: mariadb:10.5.10
    container_name: masscan-db
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: masscan
      MARIADB_USER: masscan
      MARIADB_PASSWORD: changem3
    volumes:
      - ./src/db-structure-mysql.sql:/docker-entrypoint-initdb.d/db-structure-mysql.sql
    restart: always
