############################################################
# Dockerfile to build Nginx Installed Containers
# Based on Ubuntu 20.04 LTS
############################################################

# Set the base image to Ubuntu 
FROM ubuntu:20.04

# File Author / Maintainer
LABEL author="Sobir Akbarov <akbarovsobir94@yandex.com>"

# Update the repository
RUN apt-get update

# Install necessary tools
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install apt-utils dialog iproute2 dnsutils inetutils-ping ncat masscan nano less wget nginx -y

# Remove the default NGINX configuration file
RUN rm -v /etc/nginx/nginx.conf

# Copy a configuration file from the current directory
ADD nginx.conf /etc/nginx/

# Append "daemon off;" to the ending of the configuration
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80

# Set the default command to execute
# when creating a new container
CMD service nginx start

